sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9inmM7bgqd7mEj4WoS
    access-key-secret: e0LfexmJqQRqTdXGa2FoUeaSfsgtwD
    bucket-name: sky-take-out-zhouhui
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 10
  wechat:
    appid: wx33e5dc2146bb0686
    secret: ffb9c429e39573f5e62e833dd63f0b8a