server:
  port: 8080
spring:
  profiles:
    active: dev #激活哪个配置文件，一般来说会有dev开发环境 prod生产环境  test测试环境
  main:
    allow-circular-references: true  #意思：允许 Bean 互相循环注入，解决 SpringBoot 启动报错。但是一般来说，最好不要这么写
  datasource:
    druid:  #为什么写变量读写，当激活为dev的时候，就会读取dev中的配置
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 强制让 SpringBoot 使用【旧版兼容的路径匹配规则】，解决与 Knife4j/Swagger 的冲突，启动不报错。
                                          #SpringBoot 2.6 以前默认用：ANT_PATH_MATCHER（老规则）所有框架都兼容。
                                          # SpringBoot 2.6 以后默认改成：PATH_PATTERN_PARSER（新规则）但是 Knife4j / Swagger 不认识新规则→ 直接报空指针、启动失败！
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml   # classpath: → 从项目的资源根目录开始（就是 resources 文件夹）  mapper/ → 进入 mapper 文件夹  *.xml → 匹配所有以 .xml 结尾的文件
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}